services:
  - type: web
    name: unihive
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/unihive-1.0.0.jar
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "*"
      - key: CLOUDINARY_URL
        sync: false
